name: Trigger auto deployment for container-app-5vd6eml4muxty

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-5vd6eml4muxty-AutoDeployTrigger-5be1b475-67a0-47ca-a1b8-8d51a4d73e19.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP5VD6EML4MUXTY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP5VD6EML4MUXTY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP5VD6EML4MUXTY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP5VD6EML4MUXTY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP5VD6EML4MUXTY_REGISTRY_PASSWORD }}
          containerAppName: container-app-5vd6eml4muxty
          resourceGroup: starshottodo05138cdb
          imageToBuild: default/container-app-5vd6eml4muxty:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


